server:
  port: 8082


spring:
  application:
    name: service-file
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

file:
  upload:
    bucketName: czword
    url: http://127.0.0.1:9000
    accessKey: minioadmin
    secretKey: minioadmin

# springdoc-openapi 项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan:
        # 配置接口文档扫描包路径，每个服务的路径不同，下面是系统服务(youlai-system)的包路径
        - com.itcz.czword.file.controller

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: false
  setting:
    language: zh_cn