server:
  port: 8080
spring:
  application:
    name: service-gateway
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            # 允许请求中携带的头信息
            allowedHeaders: "*"
            # 运行跨域的请求方式
            allowedMethods: "*"
            # 跨域检测的有效期,单位s
            maxAge: 36000
      routes:
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/user/**
        - id: service-file
          uri: lb://service-file
          predicates:
            - Path=/file/**
        - id: service-interface
          uri: lb://service-interface
          predicates:
            - Path=/interface/**
        - id: service-interface-api
          uri: lb://service-interface-api
          predicates:
            - Path=/api/**
        - id: service-order
          uri: lb://service-order
          predicates:
            - Path=/order/**


knife4j:
  gateway:
    # 是否开启
    enabled: true
    # 排序规则(tag/operation排序自4.2.0版本新增)
    # 取值：alpha-默认排序规则，官方swagger-ui默认实现,order-Knife4j提供的增强排序规则，开发者可扩展x-order，根据数值来自定义排序
    tags-sorter: order
    operations-sorter: order
    # 指定服务发现的模式聚合微服务文档，并且是默认`default`分组
    strategy: discover
    # 子服务存在其他分组情况，聚合其他分组，只能手动配置
    discover:
      version: openapi3
      enabled: true

